services:
  servidor:
    container_name: container_goodbye
    image: goodbye
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: baseOfLi
    ports:
      - "${PORT}:${PORT}"
